# Generated by Django 4.0 on 2021-12-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='session_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='the_eye.session'),
        ),
    ]
