# Generated by Django 4.0 on 2021-12-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
