# Generated by Django 4.0 on 2021-12-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0005_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
    ]
