# Generated by Django 4.0 on 2021-12-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0006_alter_event_options_remove_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='the_eye.time'),
        ),
    ]
