# Generated by Django 4.0 on 2021-12-26 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0011_alter_event_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['-timestamp']},
        ),
    ]
