# Generated by Django 4.0 on 2021-12-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0012_alter_time_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_by_category', to='the_eye.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_by_session', to='the_eye.session'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_by_time', to='the_eye.time'),
        ),
    ]
